# Generated by Django 4.2.13 on 2024-06-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_penilaian_kelas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengguna',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='foto_pengguna/'),
        ),
    ]
