# Generated by Django 4.2.13 on 2024-06-24 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_project_mentor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailtransaksi',
            name='tipe_kelas',
        ),
    ]
