# Generated by Django 4.2.13 on 2024-06-24 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_detailtransaksi_tipe_kelas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kelas',
            name='tipe_kelas',
        ),
        migrations.AddField(
            model_name='detailtransaksi',
            name='tipe_kelas',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
