# Generated by Django 4.2.13 on 2024-06-24 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_kelas_tipe_kelas_detailtransaksi_tipe_kelas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kelas',
            name='kategori_kelas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kelas_detail', to='home.kategori'),
        ),
    ]
