# Generated by Django 4.2.13 on 2024-06-24 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_mentor_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='usia',
            field=models.IntegerField(default=0),
        ),
    ]
