# Generated by Django 4.2.13 on 2024-06-24 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_mentor_usia'),
    ]

    operations = [
        migrations.AddField(
            model_name='kelas',
            name='tipe_kelas',
            field=models.CharField(choices=[('hybrid', 'hybrid'), ('online', 'online'), ('offline', 'offline')], default='online', max_length=10),
        ),
    ]
