# Generated by Django 4.2.13 on 2024-06-24 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_kelas_tipe_kelas'),
    ]

    operations = [
        migrations.AddField(
            model_name='kelas',
            name='silabus',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
