# Generated by Django 4.2.13 on 2024-06-24 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_kelas_silabus'),
    ]

    operations = [
        migrations.AddField(
            model_name='kelas',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='foto_kelas/'),
        ),
    ]
