# Generated by Django 4.2.13 on 2024-06-24 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_kelas_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='metode_pembayaran',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.metodepembayaran'),
        ),
    ]
