# Generated by Django 4.2.13 on 2024-06-24 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_mentor_metode_pembayaran'),
    ]

    operations = [
        migrations.AddField(
            model_name='paketkelas',
            name='jumlah_pertemuan',
            field=models.IntegerField(default=1),
        ),
    ]
