# Generated by Django 4.2.13 on 2024-06-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_paketkelas_jumlah_pertemuan'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='alamat',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
