# Generated by Django 4.2.13 on 2024-06-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_transaksi_alamat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='bukti_pembayaran',
            field=models.ImageField(blank=True, null=True, upload_to='bukti_pembayaran/'),
        ),
    ]
