# Generated by Django 4.2.13 on 2024-06-24 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_transaksi_bukti_pembayaran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='status',
            field=models.CharField(choices=[('menunggu', 'menunggu'), ('lunas', 'lunas'), ('belum lunas', 'belum lunas')], max_length=20),
        ),
    ]
